name:                dirsync
version:             0.1.0.0
github:              "githubuser/dirsync"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dirsync#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson >= 1.3 && < 1.5
    - directory >= 1.3 && < 1.4
    - unix >= 2.7 && < 2.8
    - transformers >= 0.5 && < 0.6
    - filepath >= 1.4 && < 1.5

executables:
  dirsync-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - dirsync
      - directory >= 1.3 && < 1.4
      - aeson >= 1.3 && < 1.5
      - bytestring >= 0.10 && < 0.11
tests:
  dirsync-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dirsync
